#!/usr/bin/env bash

swift-format format \
  --recursive \
  --parallel \
  --in-place \
  --configuration config/swift-format.json \
  P2PKit/Sources/ \
  P2PKit/Tests/ \
  P2PKit/Package.swift \
  P2PChat